### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [nanomixer/nanomixer#2]
Hi there, 1st of all an heartfelt thanks for what you do !

Since we've collected this repository in the [Resources section](https://github.com/forart/RecRack/blob/main/README.md#resources-fpga---other) \ [FPGA subsection](https://github.com/forart/RecRack/tree/main#fpga-) in our [RecRack project](https://github.com/forart/RecRack#readme), can you please add a GH-compliant license file ?

As you know, expliciting licensing terms is extremely important to let anyone better/faster understand how to reuse/adapt/modify your "sources" (and not only) in other open projects and vice-versa.

Although it may _sounds_ like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/nanomixer/nanomixer/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/nanomixer/nanomixer/?label=LICENSE)

Anyway you can easily set a standard one through the GH's license wizard tool.

Please let us also know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Last but not least, check out [this Hackaday.io list](https://hackaday.io/list/164050-recrack-resources) for possible ideas/collaborations.

Thanks in advance.

**Comment by kcarnold** [comment]
Cool to see others picking up on this idea. I added a License file.

If you're trying to actually use this code, it's probably easiest to jump on a quick call and I (or perhaps Martin) can explain what we remember.
